language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-25.0.3

    - android-25

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-25

    - sys-img-armeabi-v7a-android-22
